### ISSUE TITLE
Have you considered using search box as you goto issue box as well?

### ISSUE THREAD

**Issue by rouilj** [savchuk1985/roundup-jinja2-templates#1]
I like your tracker implementation. It looks much more modern than any of the distributed roundup templates.

I noticed that you kept the goto issue and search boxes. Have you considered combining them?

See:

   https://rouilj.dynamic-dns.net/fossil/roundup_sysadmin/doc/trunk/html/sysadmin_help/sysadmin.html#the-left-hand-menu

for a description of a combined quick search/issue jump/object retrieval box.

The implementation is at:

  https://rouilj.dynamic-dns.net/fossil/roundup_sysadmin/file?name=extensions/jumpSearch.py&ci=tip

This should free up some space in the top menu.

Also I assume you restricted the goto issue box to a numeric type. The increment/decrement arrows are a nice side effect, but unlikely to be used IMO. I can't image anybody using them once you reach 100 or so issues.

**Comment by savchuk1985** [comment]
Hello! Thank you very much for taking the time to leave a review.

Initially I just wanted to make small changes and update the Bootstrap version. Then I discovered that there was more work than I expected. So I avoided adding any extensions that would change the current behavior.

The combined boxes look interesting, thanks. But for now I would like to suggest replacing the current Roundup jinja2 based templates with these templates. Are there any plans to add this extension to the main Roundup repository?

> This should free up some space in the top menu.

This free space can only be used for a wider search field. Navigation items are placed on the right when using a wide screen and appear in the "off-canvas" menu on mobile devices. All user related links have been moved to the user menu. In fact, we can only choose how many input fields to place there.

> Also I assume you restricted the goto issue box to a numeric type. The increment/decrement arrows are a nice side effect, but unlikely to be used IMO. I can't image anybody using them once you reach 100 or so issues

Yes, I have set the type to "number" for this input field. Browsers automatically add arrows for this type. I don't expect anyone to use these arrows, but I want to limit the values ​​that can be submitted on this form. When I first installed Roundup, I did not immediately understand the purpose of this field. This limitation will make it more intuitive.

**Comment by rouilj** [comment]
> Hello! Thank you very much for taking the time to leave a review.

Certainly, my live Google search notified me about it.

> Initially I just wanted to make small changes and update the Bootstrap version. Then I
> discovered that there was more work than I expected. So I avoided adding any
> extensions that would change the current behavior.

Yeah. There have been a few people who have worked with that template. I know some
improvements were made for responsiveness, but none made them back upstream.

> The combined boxes look interesting, thanks.
> > This should free up some space in the top menu.
> This free space can only be used for a wider search field.

When I resize or magnify my desktop, the placeholder in the issue entry box gets truncated
and is unreadable. I must not be small enough to trigger the breakpoint where the hamburger
menu is used, but I am too large to prevent the issue text box from being shrunk.

Getting a wider search field is also a win. A wider box is great if you use sqlite or postgres native text
search which allows operators and expressions. Being able to see the whole expression without having to scroll is useful.

>> Also I assume you restricted the goto issue box to a numeric type.
> Yes, I have set the type to "number" for this input field. Browsers automatically add arrows
> [...] I want to limit the values ​​that can be submitted on this form.
> When I first installed Roundup, I did not immediately understand the purpose of this field.
> This limitation will make it more intuitive.

Yeah, a pattern can validate that the input is numeric but it allows text to be entered.
Using inputmode does pop up a numeric keypad on touch devices but doesn't do anything
useful on a desktop. It's numeric data but it is not really a number (adding two issues ids doesn't
make sense 8-)). There isn't a good semantic way to represent this. I guess the spinner
is the best affordance we have.
